FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY web/requirements.txt /app/web/requirements.txt

RUN pip install --no-cache-dir -r /app/web/requirements.txt

COPY . /app

CMD ["uvicorn", "web.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
